version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    command: -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: badpassword
      POSTGRES_USER: k6
      POSTGRES_DB: k6
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1024M
        reservations:
          cpus: '4.0'
          memory: 512M
  k6:
    image: k6-runner
    restart: no
    depends_on:
      - db
    profiles: [k6]
    volumes:
      - "${PWD}:${PWD}"
    working_dir: "${PWD}"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 246M
        reservations:
          cpus: '2.0'
          memory: 128M