version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    command: -c 'max_connections=200' -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_PASSWORD: badpassword
      POSTGRES_USER: k6
      POSTGRES_DB: k6
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080
    depends_on:
      - db

  k6:
    image: k6-runner
    restart: no
    depends_on:
      - db
    profiles: [k6]
    volumes:
      - "${PWD}:${PWD}"
    working_dir: "${PWD}"
